### ISSUE TITLE
no request is made for csrfURL

### ISSUE THREAD

**Issue by erpe** [abuiles/rails-csrf#12]
hi, 
i tried to include rails-csrf to my ember-app,
but somehow i dont see a request going out to the defined csrfURL, or to the default csrfURL (when not configuring the endpoint...)

i included rails-csrf in app.js and made use of the before_model hook 
see: [app.js](https://github.com/erpe/ember_list/blob/master/app/app.js)
and [route](https://github.com/erpe/ember_list/blob/master/app/routes/notes/new.coffee)

ember-cli
version: 0.1.2
node: 0.10.33     
npm: 2.1.3

**Comment by jaeming** [comment]
I had a similar issue. Then I created an application.js in my routes folder and put it there and it worked fine. The result is it makes unneeded GET requests to the CSRF endpoint sometimes but at least it's there when I need it.

**Comment by copasetickid** [comment]
@jaeming do you have sample app repo you can link to a reference as I'm unable to get this to work either  even when I go by your last comment.

**Comment by abuiles** [comment]
@copasetickid I've been using it in a toy project of mine, check it out here https://github.com/abuiles/facturas-client/blob/master/app/app.js#L20 and see the package.json

**Comment by copasetickid** [comment]
@abuiles I'm unable to resolve this issue I believe it may be related to this issue #14 
as the only time the request is made when I enter my application from the route, as I drill to where the form lives on the new route, etc the token no longer exists and I receive that error from by separate rails backend server.   

I would to help solve this issue and document how this can be avoided going forward.
