### ISSUE TITLE
TypeError: this.csrf is undefined

### ISSUE THREAD

**Issue by ballPointPenguin** [abuiles/rails-csrf#16]
Following the instruction in the README exactly.
my application route has no csrf object or method defined on 'this', inside the beforeModel hook.

Using ember-cli 0.1.9
rails 4.2.0

**Comment by DVG** [comment]
Did you restart your ember server after installing the addon?

**Comment by ballPointPenguin** [comment]
Unsure. I took a different approach in the end and so I don't have anything useful to contribute to this issue anymore. If nobody else experiences this issue, I think it could be closed.

**Comment by abuiles** [comment]
Sorry for the late reply, you had to call the initializer, I think I'm just going to make it run automatically and read from the config also automatically.
