### ISSUE TITLE
Integration tests fail anyway

### ISSUE THREAD

**Issue by pjmorse** [abuiles/rails-csrf#17]
Our integration tests are failing [as described in the README](https://github.com/abuiles/rails-csrf#working-with-integration-tests). I've incorporated the Pretender snippet into the `setup` block of the relevant integration test module, and through some debugging I've established that it's being called and returning a token string. However, the error keeps happening, and I'm wondering if there's something more going on.

This is what's in our ApplicationRoute:

    export default Ember.Route.extend({
      beforeModel: function() {
        return this.csrf.fetchToken();
      }
    });

This is the test setup block:

    module('Integration: Wizard navigation', {
      setup: function() {
        var server = new Pretender(function() {
          this.get('/schl/api/csrf', function(request) {
            return [200, {"Content-Type": "application/json"},
              JSON.stringify({
                "authenticity_token": "token"
              })
            ];
          });
        });
        App = startApp();
      },
      teardown: function() {
        Ember.run(App, App.destroy);
      }
    });

I've used both the bald string "token" and a token string from the API as the return value, and neither has been any more helpful than the other.

The `this.csrf.fetchToken();` call in the ApplicationRoute returns a promise, which seems like expected behavior to me, but I wonder if the error is from a failure to resolve that promise somehow? What am I doing wrong here, if anything?

**Comment by pjmorse** [comment]
I was ultimately able to resolve this by updating to ember-cli 0.2.0, ember 1.10.0, and Pretender 0.6.0 (ember-cli-pretender and/or Bower installs 0.1.0 for some reason). Should those requirements be documented?

**Comment by abuiles** [comment]
@pjmorse I release a new version last night which removes the option to fetch the CSRF token via GET, only it will set it up if you include the tags in the body.  

For development I'd recommend to turn off forgery_protection.
