### ISSUE TITLE
Clarification on removing GET /api/csrf

### ISSUE THREAD

**Issue by MattNguyen** [abuiles/rails-csrf#19]
I'm a little confused by the current state of this add-on package due to https://github.com/abuiles/rails-csrf/commit/256842ca436beeec6deee534a2d80976cbc57522. What was the rationale for the removal of the API call to fetch the CSRF token?

Furthermore, the docs mention that you must include a static CSRF token. Why is this? Seems like this would defeat the purpose of server generated CSRF tokens if you're able to pass arbitrary values to the server.

Thanks!

**Comment by abuiles** [comment]
Just replied to you via email, if someone else wants to know the reason behind this please send me an email to builes.adolfo@gmail.com

**Comment by 3v0k4** [comment]
Hey @abuiles  can you elaborate on this publicly please?

**Comment by abuiles** [comment]
@3v0k4 please send me an email

**Comment by jayswain** [comment]
Hey @abuilies, sent you an email as well. awaiting your response.

**Comment by krzkrzkrz** [comment]
Send you an email too

**Comment by jayswain** [comment]
@krzkrzkrz FYI - I have not received a response from @abuiles yet.

**Comment by mszoernyi** [comment]
I think it would make more sense to post some details here instead of asking ppl to send you a email to get details...

**Comment by krzkrzkrz** [comment]
@jayswain It's not my line to give out the reason. The author did communicate it out to me though. It's not for me to say. I think it would be best to leave it to the author to decide if or how he should communicate the details. You can also try reaching him on irc/freenode server, #ember-cli channel.

Don't get me wrong. I do agree, some public details would be convenient for others.

**Comment by abuiles** [comment]
I'm not longer maintaining this library, if someone wants to take over feel free to ping me https://github.com/abuiles/rails-csrf/commit/24fc8d21bd44576d9fcf0a4ffdbd7089f232a414
