### ISSUE TITLE
Broken in Ember-CLI 0.2.2?

### ISSUE THREAD

**Issue by krzkrzkrz** [abuiles/rails-csrf#20]
I've upgraded to Ember-CLI 0.2.2.

I am following the readme at https://github.com/abuiles/rails-csrf. i.e.

    Add a meta tag like the following to your app body and the addon will do the rest:
    <meta content="adfadfadsfi34/sdfadfadf=" name="csrf-token">

I refresh the page, the `meta` tag's content value does not change to anything. As if the plugin isn't working. I also don't see the any api attempts to the csrf api endpoint. The network tab of Ember Inspector doesn't show anything relative.

Is the readme missing a step?

**Comment by skanderm** [comment]
Same problem here. This is also with 0.2.2.

**Comment by skanderm** [comment]
@krzkrzkrz The addon seems to assume that the meta tag is actually provided in your Rails template via `<%= csrf_meta_tags %>` and no longer makes a call to a `/csrf` endpoint. You probably need to downgrade to a previous version to get that functionality again.

Also, https://www.npmjs.com/package/rails-csrf seems out of date.

**Comment by efries** [comment]
btw, <%= csrf_meta_tags %> output is similar to:
<meta content="adfadfadsfi34/sdfadfadf=" name="csrf-token">

**Comment by krzkrzkrz** [comment]
@skanderm if the addon assumes that the meta tag is included in a Rails template. How is that even possible if one is using Ember CLI (Single Page Application), where the client handles all of the "templates/views" and Rails just acts as an API.

For single page applications, should we just query the API for the csrf token?

**Comment by skanderm** [comment]
@krzkrzkrz Yeah, I went back to doing that, I'm back to v1.0.1 now.

**Comment by samjulien** [comment]
I'm in the middle of this same problem. @krzkrzkrz, how are you querying the API for the csrf token? @skanderm, did you go back to v.1.0.1 of rails-csrf? Thanks!

**Comment by skanderm** [comment]
Yep @samjulien, on v1.0.1. You can create a `/csrf` endpoint on your API that looks like

```
class CsrfController < ApplicationController
  def index
    render json: { request_forgery_protection_token => form_authenticity_token }.to_json
  end
end
```

Check out the previous versions of the readme.

**Comment by samjulien** [comment]
Ah, thanks, I'll give that a shot.

**Comment by samjulien** [comment]
@skanderm Is there something different I need to do in app.js to load the initializer or import rails-csrf? I'm getting `Error while processing route: index Cannot read property 'fetchToken' of undefined TypeError: Cannot read property 'fetchToken' of undefined` when I try to load the page.

All I've done in app.js is what the readme recommended:

```js
loadInitializers(App, 'rails-csrf');
```

Thanks in advance!

**Comment by skanderm** [comment]
Maybe try it it it's own call after the first?

```
loadInitializers(App, config.modulePrefix);
loadInitializers(App, 'rails-csrf');
```

**Comment by samjulien** [comment]
@skanderm forgot to thank you for this - rails-csrf is working, just gotta wrestle with rack now. Cheers!

**Comment by krzkrzkrz** [comment]
@samjulien at this point, I dont think querying the API for a csrf token is the best approach. It leaves the application vulnerable

**Comment by abuiles** [comment]
As @krzkrzkrz mentioned, querying the API is not recommended because of possible vulnerabilities, the recommended way is to disable CSRF in dev and then enable in production and make sure you inject the CSRF token in the body when booting up the app
